[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "reflective-ai"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
